[package]
name = "emo"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
